services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5431:5432"
      # Host :  Container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Auth_in_ts_DB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: